server:
  port: 9999

spring:
  application:
    name: external-data-service
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: validate
        show_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        default_schema: public
        auto_quote_keyword: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/external_data_service
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
      percentiles-histogram:
        http.server.requests: true
      minimum-expected-value:
        http.server.requests: 100ms
      maximum-expected-value:
        http.server.requests: 10s
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms

logging:
  level:
    ru.elias.external: DEBUG