server:
  port: 8082

spring:
  application:
    name: data-generation-service

data:
  service:
    external-service:
      base-uri: http://localhost:9191/api/v1/data

logging:
  level:
    ru.elias.data: DEBUG