server:
  port: 8085

spring:
  application:
    name: report-delivery-service

mail:
  host: smtp.gmail.com
  port: 587
  username: mallet322@gmail.com
  password: etmw lklq vymu tlmw
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
      debug: true
  subject: "[report-generate-system] Your Report"
  text: "Please check the attached report."
  attachment-name: "report-%s"

services:
  report-data-service:
    base-uri: http://localhost:8083/reports

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
      percentiles-histogram:
        http.server.requests: true
      minimum-expected-value:
        http.server.requests: 100ms
      maximum-expected-value:
        http.server.requests: 10s
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms