server:
  port: 8085

spring:
  application:
    name: report-delivery-service

mail:
  host: smtp.gmail.com
  port: 587
  username: mallet322@gmail.com
  password: etmw lklq vymu tlmw
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
      debug: true
  subject: "[report-generate-system] Your Report"
  text: "Please check the attached report."
  attachment-name: "report-%s"

services:
  report-data-service:
    base-uri: http://localhost:8083/reports