apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest
        command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Service
metadata:
  name: curl-service
  namespace: dev
spec:
  selector:
    app: curl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80