apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
stringData:
  secret.yml: |
    keycloak:
      token:
        client: {{ .Values.keycloak.token.client.clientId }}
        client-secret: {{ .Values.keycloak.token.client.clientSecret }}
      admin:
        client: {{ .Values.keycloak.token.admin.clientId }}
        client-secret: {{ .Values.keycloak.token.admin.clientSecret }}