apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
stringData:
  secret.yml: |
    keycloak:
      token:
        client: health
        client-secret: UySC5zBFUGU0ZkIIZ2PYf0ujlBd4897i
      admin:
        client: admin-cli
        client-secret: 1bqDA10GoZfRnEaj9zhTKlfK0IpQPi5f