apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
stringData:
  secret.yml: |
    keycloak:
      token:
        client: health
        client-secret: lOLb22HxdIFibLOCLzUQpAFQbeXgql72
      admin:
        client: admin-cli
        client-secret: fd3dPFvHWkA1hP5DGkLhgQTSW3X2EG8k