apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "_helpers-report-generator-service.name" . }}
data:
  application.yml: |
    server:
      port: {{ .Values.service.port }}
    spring:
      application:
        name: {{ include "_helpers-report-generator-service.name" . }}
    service:
      data-generation-service:
        base-uri: {{ .Values.data.service.dataGenerationService.baseUri }}
      report-data-service:
        base-uri: {{ .Values.data.service.reportDataService.baseUri }}
      config-control-service:
        base-uri: {{ .Values.data.service.configControlService.baseUri }}
    management:
      endpoints:
        web:
          exposure:
            include: health, metrics, prometheus
      metrics:
        distribution:
          percentiles:
            http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
          percentiles-histogram:
            http.server.requests: true
          minimum-expected-value:
            http.server.requests: 100ms
          maximum-expected-value:
            http.server.requests: 10s
          slo:
            http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms
    logging:
      level:
        ru.elias.reportgenerator: DEBUG