replicaCount: 1

image:
  repository: malletmustdie/report-generator-service
  pullPolicy: Always
  tag: "0.1.3"

service:
  type: ClusterIP
  port: 8080

serviceAccount: data-generation-service-user

data:
  service:
    dataGenerationService:
      baseUri: http://data-generation-service:8080/api/v1/warehouse
    reportDataService:
      baseUri: http://report-data-service:8080/reports/upload
    configControlService:
      baseUri: http://config-control-service:8080/api/v1/configs

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "1Gi"
    cpu: "400m"