replicaCount: 1

image:
  repository: malletmustdie/report-generator-service
  pullPolicy: Always
  tag: "0.1.2"

service:
  type: ClusterIP
  port: 8080

serviceAccount: data-generation-service-user

data:
  service:
    dataGenerationService:
      baseUri: http://data-generation-service:8080/api/v1/warehouse

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "1Gi"
    cpu: "400m"