apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
stringData:
  secret.yml: |
    spring:
      datasource:
        url: jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.db }}
        username: {{ .Values.database.username }}
        password: {{ .Values.database.password }}