apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "_helpers.external-data-service.name" . }}
  labels:
    app.kubernetes.io/namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "_helpers.external-data-service.name" . }}
  endpoints:
    {{- include "_helpers.external-data-service.service-monitor.endpoints" . | nindent 4 }}