replicaCount: 1

image:
  repository: malletmustdie/api-gateway
  pullPolicy: Always
  tag: "0.1.7"

service:
  type: ClusterIP
  port: 8080

serviceAccount: api-gateway-user

data:
  services:
    configControlService:
      baseUri: http://config-control-service:8080/api/v1/configs
    reportGeneratorService:
      baseUri: http://report-generator-service:8080/api/v1/reports
    reportDeliveryService:
      baseUri: http://report-delivery-service:8080/api/v1/delivery

keycloak:
  authUrl: http://keycloak-keycloakx-http:80/auth
  realm: health-realm

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "1Gi"
    cpu: "400m"