replicaCount: 1

image:
  repository: malletmustdie/api-gateway
  pullPolicy: Always
  tag: "0.1.1"

service:
  type: ClusterIP
  port: 8080

serviceAccount: api-gateway-user

data:
  service:
    configControlService:
      baseUri: http://config-control-service:8080/api/v1/configs
    reportGeneratorService:
      baseUri: http://report-generator-service:8080/api/v1/reports

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "1Gi"
    cpu: "400m"