apiVersion: v1
kind: Service
metadata:
  name: {{ include "_helpers-report-delivery-service.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "_helpers-report-delivery-service.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "_helpers-report-delivery-service.name" . }}