server:
  port: 8081

spring:
  application:
    name: report-generator-service

service:
  data-generation-service:
    base-uri: http://localhost:8082/api/v1/warehouse
  report-data-service:
    base-uri: http://localhost:8083/reports/upload
  config-control-service:
    base-uri: http://localhost:8084/api/v1/configs

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
      percentiles-histogram:
        http.server.requests: true
      minimum-expected-value:
        http.server.requests: 100ms
      maximum-expected-value:
        http.server.requests: 10s
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms, 600ms, 800ms

logging:
  level:
    ru.elias.reportgenerator: DEBUG