replicaCount: 1

image:
  repository: malletmustdie/data-generation-service
  pullPolicy: Always
  tag: "0.1.3"

service:
  type: ClusterIP
  port: 8080

serviceAccount: data-generation-service-user

data:
  service:
    externalService:
      baseUri: http://external-data-service:8080/api/v1/data

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "1Gi"
    cpu: "400m"