replicaCount: 1

image:
  repository: malletmustdie/external-data-service
  pullPolicy: Always
  tag: "0.1.1"

service:
  type: ClusterIP
  port: 8080

serviceAccount: external-data-service-user

database:
  host: postgres-postgresql
  port: 5432
  db: external_data_service

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "1Gi"
    cpu: "400m"